### ISSUE TITLE
Alignment goes into infinite loop if force to non-existent version present

### ISSUE THREAD

**Issue by DanielThomas** [nebula-plugins/gradle-resolution-rules-plugin#55] opened 2017-04-03 19:26 UTC
We need to fail when we get unresolvable dependencies to prevent this from happening.

**Comment by rspieldenner** [comment] 2017-05-02 22:11
closing this for now, can't reproduce, added tests

**Comment by DanielThomas** [comment] 2017-05-30 17:14
I can reproduce on the original project that had this issue, I just never got those tests to fail. Reopening.

**Closed** 2017-06-05 22:06 UTC
